[information]
name="ayu-light"
author="Ken Zhou <kendotzhou@gmail.com>"
background="light"

[palette]
white = "#26292f"
darker_black = "#ededed"
black = "#fafafa" #  nvim bg
black2 = "#e3e3e3"
one_bg = "#ebebeb"
one_bg2 = "#e1e1e1" # Highlight of context
one_bg3 = "#d7d7d7"
grey = "#cdcdcd"
grey_fg = "#b9b9b9"
grey_fg2 = "#acacac" # Highlight background
light_grey = "#a0a0a0" # Line numbers
red = "#E65050"
baby_pink = "#ff8282"
pink = "#ffa5a5"
line = "#e1e1e1" # for lines like vertsplit
green = "#6CBF43"
vibrant_green = "#94e76b"
blue = "#399EE6"
nord_blue = "#2c91d9"
yellow = "#E6BA7E"
sun = "#f3c78b"
purple = "#9F40FF"
dark_purple = "#8627e6"
teal = "#74c5aa"
orange = "#FA8D3E"
cyan = "#95E6CB"
statusline_bg = "#f0f0f0"
lightbg = "#e6e6e6"
pmenu_bg = "#95E6CB"
folder_bg = "#5C6166"
base00 = "#fafafa"
base01 = "#f0f0f0"
base02 = "#e6e6e6"
base03 = "#dcdcdc"
base04 = "#d2d2d2"
base05 = "#5C6166"
base06 = "#52575c"
base07 = "#484d52"
base08 = "#F07171"
base09 = "#A37ACC"
base0A = "#399EE6"
base0B = "#86B300"
base0C = "#4CBF99"
base0D = "#55B4D4"
base0E = "#FA8D3E"
base0F = "#F2AE49"

[highlights]
Normal = 'base05 base00'
SignColumn = 'base03 - - -'
MsgArea = 'base05 base00'
ModeMsg = 'base0B'
MsgSeparator = 'base05 base00'
SpellBad = '- - c base08'
SpellCap = '- - c base0D'
SpellLocal = '- - c base0C'
SpellRare = '- - c base0D'
NormalNC = 'base05 base00'
Pmenu = '- one_bg'
PmenuSel = 'black pmenu_bg'
WildMenu = 'base08 base0A'
CursorLineNr = 'white'
Comment = 'grey_fg'
Folded = 'base03 base01'
FoldColumn = 'base0C base01'
LineNr = 'grey'
FloatBorder = 'blue'
# Whitespace = 'base00 -'
VertSplit = 'line'
CursorLine = '- base01'
CursorColumn = '- base01'
ColorColumn = '- base01'
NormalFloat = '- darker_black'
Visual = '- base02'
VisualNOS = 'base08 -'
WarningMsg = 'base08'
DiffAdd = 'vibrant_green'
DiffChange = 'blue'
DiffDelete = 'red'
QuickFixLine = '- base01 - -'
PmenuSbar = '- one_bg'
PmenuThumb = '- grey'
MatchWord = 'white grey'
MatchParen = 'link:MatchWord'
# MatchWordCur = '- - u'
# MatchParenCur = '- - u'
Cursor = 'base00 base05'
# lCursor = 'base05 base00'
# CursorIM = 'base05 base00'
# TermCursor = 'base05 base00'
# TermCursorNC = 'base05 base00'
Conceal = '- -'
Directory = 'base0D'
SpecialKey = 'base03'
Title = 'base0D - - -'
ErrorMsg = 'base08 base00'
Search = 'base01 base0A'
IncSearch = 'base01 base09'
Substitute = 'base01 base0A - -'
MoreMsg = 'base0B'
Question = 'base0D'
# EndOfBuffer = 'base00'
NonText = 'base03'
Variable = 'base05'
String = 'base0B'
Character = 'base08'
Constant = 'base08'
Number = 'base09'
Boolean = 'base09'
Float = 'base09'
Identifier = 'base08 - - -'
Function = 'base0D'
Operator = 'base05 - - -'
Type = 'base0A - - -'
StorageClass = 'base0A'
Structure = 'base0E'
Typedef = 'base0A'
Keyword = 'base0E'
Statement = 'base08'
Conditional = 'base0E'
Repeat = 'base0A'
Label = 'base0A'
Exception = 'base08'
Include = 'base0D'
PreProc = 'base0A'
Define = 'base0E - - -'
Macro = 'base08'
# PreCondit = 'purple'
Special = 'base0C'
SpecialChar = 'base0F'
Tag = 'base0A'
Debug = 'base08'
# Delimiter = 'grey -'
# SpecialComment = 'grey_fg'
Underlined = 'base0B'
Bold = '- - b'
Italic = '- - i'
Ignore = 'cyan base00 b'
Todo = 'base0A base01'
Error = 'base00 base08'
TabLine = 'light_grey line'
TabLineSel = 'white line'
TabLineFill = 'line line'

[Treesitter]
TSComment = 'link:Comment'
TSAnnotation = 'base0F'
TSAttribute = 'base0A'
TSConstructor = 'base0C'
# TSType = 'cyan'
TSTypeBuiltin = 'base0A'
TSConditional = 'link:Conditional'
TSException = 'base08'
TSInclude = 'link:Include'
TSKeywordReturn = 'base0E'
TSKeyword = 'base0E'
TSKeywordFunction = 'base0E'
# TSLabel = 'cyan'
TSNamespace = 'base08'
# TSRepeat = 'yellow'
# TSConstant = 'orange'
TSConstBuiltin = 'base09'
TSFloat = 'base09'
# TSNumber = 'orange'
# TSBoolean = 'orange'
TSCharacter = 'base08'
TSError = 'base08'
TSFunction = 'base0D'
TSFuncBuiltin = 'base0D'
TSMethod = 'base0D'
TSConstMacro = 'base08'
TSFuncMacro = 'base08'
TSVariable = 'base05'
TSVariableBuiltin = 'base09'
TSProperty = 'base08'
TSField = 'base0D'
TSParameter = 'base08'
TSParameterReference = 'base05'
TSSymbol = 'base0B'
TSText = 'base05'
# TSOperator = 'base05'
TSPunctDelimiter = 'base0F'
TSTagDelimiter = 'base0F'
TSTagAttribute = 'link:TSProperty'
TSPunctBracket = 'base0F'
TSPunctSpecial = 'base08'
# TSString = 'green'
TSStringRegex = 'base0C'
TSStringEscape = 'base0C'
# TSTag = 'blue'
TSEmphasis = 'base09'
# TSUnderline = '- - u'
# TSTitle = 'base05 - -'
TSLiteral = 'base09'
TSURI = 'base09'
TSKeywordOperator = 'base0E'
# TSStructure = 'cyan'
TSStrong = '- - b'
# TSQueryLinterError = 'base09'
TreesitterContext = 'link:CursorLine'

[markdown]
markdownBlockquote = 'green'
markdownCode = 'orange'
markdownCodeBlock = 'orange'
markdownCodeDelimiter = 'orange'
markdownH1 = 'blue'
markdownH2 = 'blue'
markdownH3 = 'blue'
markdownH4 = 'blue'
markdownH5 = 'blue'
markdownH6 = 'blue'
markdownHeadingDelimiter = 'blue'
markdownHeadingRule = 'base05 - b'
markdownId = 'purple'
markdownIdDeclaration = 'blue'
markdownIdDelimiter = 'light_grey'
markdownLinkDelimiter = 'light_grey'
markdownBold = 'blue - b'
markdownItalic = '- - i'
markdownBoldItalic = 'yellow - bi'
markdownListMarker = 'blue'
markdownOrderedListMarker = 'blue'
markdownRule = 'base01'
markdownUrl = 'cyan - u'
markdownLinkText = 'blue'
markdownFootnote = 'orange'
markdownFootnoteDefinition = 'orange'
markdownEscape = 'yellow'

[Whichkey]
WhichKey = 'purple'
WhichKeySeperator = 'green'
WhichKeyGroup = 'blue'
WhichKeyDesc = 'cyan'
WhichKeyFloat = '- base01'

[Git]
SignAdd = 'green'
SignChange = 'blue'
SignDelete = 'red'
GitSignsAdd = 'green'
GitSignsChange = 'blue'
GitSignsDelete = 'red'

[LSP]
DiagnosticError = 'base08'
DiagnosticWarning = 'base09'
DiagnosticHint = 'purple'
DiagnosticWarn = 'yellow'
DiagnosticInfo = 'green'
LspDiagnosticsDefaultError = 'base08'
LspDiagnosticsDefaultWarning = 'base09'
LspDiagnosticsDefaultInformation = 'sun'
LspDiagnosticsDefaultInfo = 'sun'
LspDiagnosticsDefaultHint = 'purple'
LspDiagnosticsVirtualTextError = 'base08'
LspDiagnosticsVirtualTextWarning = 'base09'
LspDiagnosticsVirtualTextInformation = 'sun'
LspDiagnosticsVirtualTextInfo = 'sun'
LspDiagnosticsVirtualTextHint = 'purple'
LspDiagnosticsFloatingError = 'base08'
LspDiagnosticsFloatingWarning = 'base09'
LspDiagnosticsFloatingInformation = 'sun'
LspDiagnosticsFloatingInfo = 'sun'
LspDiagnosticsFloatingHint = 'purple'
DiagnosticSignError = 'base08'
DiagnosticSignWarning = 'base09'
DiagnosticSignInformation = 'sun'
DiagnosticSignInfo = 'sun'
DiagnosticSignHint = 'purple'
LspDiagnosticsSignError = 'base08'
LspDiagnosticsSignWarning = 'base09'
LspDiagnosticsSignInformation = 'sun'
LspDiagnosticsSignInfo = 'sun'
LspDiagnosticsSignHint = 'purple'
LspDiagnosticsError = 'base08'
LspDiagnosticsWarning = 'base09'
LspDiagnosticsInformation = 'sun'
LspDiagnosticsInfo = 'sun'
LspDiagnosticsHint = 'purple'
LspDiagnosticsUnderlineError = '- - u'
LspDiagnosticsUnderlineWarning = '- - u'
LspDiagnosticsUnderlineInformation = '- - u'
LspDiagnosticsUnderlineInfo = '- - u'
LspDiagnosticsUnderlineHint = '- - u'
LspReferenceRead = '- #2e303b'
LspReferenceText = '- #2e303b'
LspReferenceWrite = '- #2e303b'
LspCodeLens = 'base04 - i'
LspCodeLensSeparator = 'base04 - i'

[Telescope]
TelescopeNormal = '- darker_black'
TelescopePreviewTitle = 'black green b'
TelescopePromptTitle = 'black red b'
TelescopeResultsTitle = 'darker_black darker_black b'
TelescopeSelection = 'white black2'
# TelescopeMatching = 'sun - b'
TelescopeBorder = 'darker_black darker_black'
TelescopePromptBorder = 'black2 black2'
TelescopePromptNormal = 'white black2'
TelescopePromptPrefix = 'red black2'
TelescopeResultsDiffAdd = 'green'
TelescopeResultsDiffChange = 'blue'
TelescopeResultsDiffDelete = 'red'

[NvimTree]
NvimTreeFolderIcon = 'blue'
NvimTreeIndentMarker = '#c5c5c5'
NvimTreeNormal = '- darker_black'
NvimTreeVertSplit = 'darker_black darker_black'
NvimTreeFolderName = 'blue'
NvimTreeOpenedFolderName = 'blue - bi'
NvimTreeEmptyFolderName = 'grey - i'
NvimTreeGitIgnored = 'grey - i'
NvimTreeImageFile = 'light_grey'
NvimTreeSpecialFile = 'orange'
NvimTreeEndOfBuffer = 'darker_black'
NvimTreeCursorLine = '- #282b37'
NvimTreeGitignoreIcon = 'red'
NvimTreeGitStaged = 'vibrant_green'
NvimTreeGitNew = 'vibrant_green'
NvimTreeGitRenamed = 'vibrant_green'
NvimTreeGitDeleted = 'red'
NvimTreeGitMerge = 'blue'
NvimTreeGitDirty = 'blue'

NvimTreeSymlink = 'cyan'
NvimTreeRootFolder = 'base05 - b'
NvimTreeExecFile = 'green'

[Buffer]
BufferCurrent = 'base05 base00'
BufferCurrentIndex = 'base05 base00'
BufferCurrentMod = 'sun base00'
BufferCurrentSign = 'purple base00'
BufferCurrentTarget = 'red base00 b'

BufferVisible = 'base05 base00'
BufferVisibleIndex = 'base05 base00'
BufferVisibleMod = 'sun base00'
BufferVisibleSign = 'grey base00'
BufferVisibleTarget = 'red base00 b'

BufferInactive = 'grey darker_black'
BufferInactiveIndex = 'grey darker_black'
BufferInactiveMod = 'sun darker_black'
BufferInactiveSign = 'grey darker_black'
BufferInactiveTarget = 'red darker_black b'

[StatusLine]
StatusLine = 'line statusline_bg'
StatusLineNC = '- statusline_bg'
StatusLineSeparator = 'line'
StatusLineTerm = 'line'
StatusLineTermNC = 'line'

[IndentBlankline]
IndentBlanklineContextChar = 'grey'
IndentBlanklineContextStart = '- one_bg2'
IndentBlanklineChar = 'line'
IndentBlanklineSpaceChar = 'line'
IndentBlanklineSpaceCharBlankline = 'sun'

[Dashboard]
DashboardHeader = 'blue'
DashboardCenter = 'purple'
DashboardFooter = 'cyan'

[Cmp]
CmpItemAbbrDeprecated = 'grey - s'
CmpItemAbbrMatch = 'blue'
CmpItemAbbrMatchFuzzy = 'blue'
CmpItemKindFunction = 'blue'
CmpItemKindMethod = 'blue'
CmpItemKindConstructor = 'cyan'
CmpItemKindClass = 'cyan'
CmpItemKindEnum = 'cyan'
CmpItemKindEvent = 'yellow'
CmpItemKindInterface = 'cyan'
CmpItemKindStruct = 'cyan'
CmpItemKindVariable = 'red'
CmpItemKindField = 'red'
CmpItemKindProperty = 'red'
CmpItemKindEnumMember = 'orange'
CmpItemKindConstant = 'orange'
CmpItemKindKeyword = 'purple'
CmpItemKindModule = 'cyan'
CmpItemKindValue = 'base05'
CmpItemKindUnit = 'base05'
CmpItemKindText = 'base05'
CmpItemKindSnippet = 'yellow'
CmpItemKindFile = 'base05'
CmpItemKindFolder = 'base05'
CmpItemKindColor = 'base05'
CmpItemKindReference = 'base05'
CmpItemKindOperator = 'base05'
CmpItemKindTypeParameter = 'red'

[ToggleTerm]
ToggleTerm1FloatBorder = 'line'

[Illuminate]
IlluminatedWordText = '- base02 - -'
IlluminatedWordRead = '- base02 - -'
